# CORE
FROM node:18-alpine as develop-stage-core
WORKDIR /app
COPY ./mf-core/package*.json ./
RUN npm install -g @quasar/cli
COPY ./mf-core .

# build stage
FROM develop-stage-core as build-stage-core
RUN npm install
RUN quasar build

# CONVALIDACIONS
FROM node:18-alpine as develop-stage-convalidacions
WORKDIR /app
COPY ./mf-convalidacions/package*.json ./
RUN npm install -g @quasar/cli
COPY ./mf-convalidacions .

# build stage
FROM develop-stage-convalidacions as build-stage-convalidacions
RUN npm install
RUN quasar build

# GRUPS COOPERATIUS
FROM node:18-alpine as develop-stage-grupscooperatius
WORKDIR /app
COPY ./mf-grupscooperatius/package*.json ./
RUN npm install -g @quasar/cli
COPY ./mf-grupscooperatius .

# build stage
FROM develop-stage-grupscooperatius as build-stage-grupscooperatius
RUN npm install
RUN quasar build

# RESERVES
FROM node:18-alpine as develop-stage-reserves
WORKDIR /app
COPY ./mf-reserves/package*.json ./
RUN npm install -g @quasar/cli
COPY ./mf-reserves .

# build stage
FROM develop-stage-reserves as build-stage-reserves
RUN npm install
RUN quasar build

# PROFESSORAT MANAGER
FROM node:18-alpine as develop-stage-professorat-manager
WORKDIR /app
COPY ./mf-professorat-manager/package*.json ./
RUN npm install -g @quasar/cli
COPY ./mf-professorat-manager .

# build stage
FROM develop-stage-professorat-manager as build-stage-professorat-manager
RUN npm install
RUN quasar build

# # production stage
FROM nginx:1.23.4-bullseye as production-stage

COPY /nginx-gateway/default.conf /etc/nginx/conf.d/default.conf
COPY --from=build-stage-core /app/dist/spa /usr/share/nginx/html/usuaris

# Esborrar si el projecte no fa servir aquest mòdul.
#El projecte gestsuite-autoinstall ho esborra automàticament, sinó s'ha de fer manualment
COPY --from=build-stage-convalidacions /app/dist/spa /usr/share/nginx/html/convalidacions

# Esborrar si el projecte no fa servir aquest mòdul.
#El projecte gestsuite-autoinstall ho esborra automàticament, sinó s'ha de fer manualment
COPY --from=build-stage-professorat-manager /app/dist/spa /usr/share/nginx/html/professorat-manager

# Esborrar si el projecte no fa servir aquest mòdul.
#El projecte gestsuite-autoinstall ho esborra automàticament, sinó s'ha de fer manualment
COPY --from=build-stage-grupscooperatius /app/dist/spa /usr/share/nginx/html/grupscooperatius

# Esborrar si el projecte no fa servir aquest mòdul.
#El projecte gestsuite-autoinstall ho esborra automàticament, sinó s'ha de fer manualment
COPY --from=build-stage-reserves /app/dist/spa /usr/share/nginx/html/reserves

# Instal·lem certbot pel certificat SSL
# Ho instal·lem amb PIP i no Snap (com recomana) perquè en entorns virtualitzats Snap no funciona
# Més info: https://certbot.eff.org/instructions?ws=nginx&os=pip
RUN apt update
RUN apt upgrade -y
RUN apt install python3 python3-venv libaugeas0 -y
RUN python3 -m venv /opt/certbot/
RUN /opt/certbot/bin/pip install --upgrade pip
RUN /opt/certbot/bin/pip install certbot certbot-nginx
RUN ln -s /opt/certbot/bin/certbot /usr/bin/certbot
RUN echo "0 0,12 * * * root /opt/certbot/bin/python -c 'import random; import time; time.sleep(random.random() * 3600)' && certbot renew -q" | tee -a /etc/crontab > /dev/null

# IMPORTANT: a partir d'aquí executar "certbot --nginx" manualment

CMD ["nginx", "-g", "daemon off;"]
